name: delibery_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.4.3+1
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  provider: ^5.0.0
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+4
  shared_preferences: ^2.2.3

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
