// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp7Ou5BJU416h_gadwatIYm_2a-AWblNY',
    appId: '1:42695295892:web:a65f87fe447a49d8c8c581',
    messagingSenderId: '42695295892',
    projectId: 'delibery-flutter',
    authDomain: 'delibery-flutter.firebaseapp.com',
    storageBucket: 'delibery-flutter.appspot.com',
    measurementId: 'G-JS0T0TQP1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw0OR1TYk1ZamFyLd9oHgXJ6y1x4FVOhM',
    appId: '1:42695295892:android:76a9c125aae76428c8c581',
    messagingSenderId: '42695295892',
    projectId: 'delibery-flutter',
    storageBucket: 'delibery-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCzrF20eTk6qNpUwZb252eFxyxMcD2dOs',
    appId: '1:42695295892:ios:e52bbdd6b1aa0324c8c581',
    messagingSenderId: '42695295892',
    projectId: 'delibery-flutter',
    storageBucket: 'delibery-flutter.appspot.com',
    iosBundleId: 'com.example.deliberyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCzrF20eTk6qNpUwZb252eFxyxMcD2dOs',
    appId: '1:42695295892:ios:e52bbdd6b1aa0324c8c581',
    messagingSenderId: '42695295892',
    projectId: 'delibery-flutter',
    storageBucket: 'delibery-flutter.appspot.com',
    iosBundleId: 'com.example.deliberyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp7Ou5BJU416h_gadwatIYm_2a-AWblNY',
    appId: '1:42695295892:web:1f704e82680058b0c8c581',
    messagingSenderId: '42695295892',
    projectId: 'delibery-flutter',
    authDomain: 'delibery-flutter.firebaseapp.com',
    storageBucket: 'delibery-flutter.appspot.com',
    measurementId: 'G-GGD9R6QGNJ',
  );
}
